# Archivo optimizado para despliegue de sitio estático (HTML)
name: Build and deploy static site to Azure Web App - agustingil-obligatorio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Simplemente subimos el index.html que está en la raíz
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-site
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55B377C767FE419D9EC27911ABF805FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5E45627FB8BE4F47BA79E95CCE4D40B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E824E273A19B4CF3A9B924A726CF7DB3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agustingil-obligatorio'
          slot-name: 'Production'
          package: .
          
